

services:
  user-service:
    build: ./user_service
    container_name: user-service
    ports:
      - "4587:4587"
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - intellecta-network
    env_file:
      - .env
    restart: always

  # game-service:
  #   build: ./game-service
  #   container_name: game-service
  #   ports:
  #     - "5002:5002"
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   networks:
  #     - intellecta-network
  #   env_file:
  #     - .env
  #   restart: always

  ai-tutor-service:
    build: ./ai_tutor_service
    container_name: ai-tutor-service
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - intellecta-network
    env_file:
      - .env
    restart: always

  # qa-bot-service:
  #   build: ./qa-bot-service
  #   container_name: qa-bot-service
  #   ports:
  #     - "5004:5004"
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   networks:
  #     - intellecta-network
  #   env_file:
  #     - .env
  #   restart: always

  # insight-service:
  #   build: ./insight-service
  #   container_name: insight-service
  #   ports:
  #     - "5005:5005"
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   networks:
  #     - intellecta-network
  #   env_file:
  #     - .env
  #   restart: always

  # content-service:
  #   build: ./content-service
  #   container_name: content-service
  #   ports:
  #     - "5006:5006"
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   networks:
  #     - intellecta-network
  #   env_file:
  #     - .env
  #   restart: always

  # notification-service:
  #   build: ./notification-service
  #   container_name: notification-service
  #   ports:
  #     - "5007:5007"
  #   depends_on:
  #     - rabbitmq
  #     - mongodb
  #   networks:
  #     - intellecta-network
  #   env_file:
  #     - .env
  #   restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - intellecta-network
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - intellecta-network
    restart: always
    volumes:
      - mongodb-data:/data/db

networks:
  intellecta-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
