version: '3.8' # Optional but recommended for clarity

services:
  user-service:
    build: ./user_service
    container_name: user-service
    ports:
      - "5000:5000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - intellecta-network
    env_file:
      - .env
    restart: always

  game-service:
    build: ./game_service
    container_name: game-service
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - mongodb
    networks:
      - intellecta-network
    env_file:
      - .env
    restart: always

  ai-tutor-service:
    build: ./ai_tutor_service
    container_name: ai-tutor-service
    ports:
      - "5001:5001"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
    networks:
      - intellecta-network
    env_file:
      - .env
    restart: always

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - intellecta-network
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - intellecta-network
    restart: always
    volumes:
      - mongodb-data:/data/db

networks:
  intellecta-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local